repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # black
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --check
        language: system
        files: ^(cicd|linkedin_matrix)/.*\.pyi?$

  # isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: ^(cicd|linkedin_matrix)/.*\.pyi?$

  # flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^.*\.py$

  # custom style checks
  - repo: local
    hooks:
      - id: custom-style-check
        name: custom style check
        entry: ./cicd/custom_style_check.py
        language: python
        additional_dependencies:
          - termcolor==2.1.1
