[tool.poetry]
name = "mautrix-linkedin"
version = "0.1.0"
description = "LinkedIn Mesaging <-> Matrix Bridge"
license = "MIT"
authors = ["Sumner Evans <inquiries@sumnerevans.com>"]
readme = "README.md"
repository = "https://git.sr.ht/~sumner/mautrix-linkedin"
keywords = ["mautrix", "matrix", "LinkedIn", "bridge"]
classifiers = [
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    "Development Status :: 3 - Alpha",
    "Topic :: Communications :: Chat",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]

[tool.poetry.scripts]
mautrix-linkedin = 'mautrix_linkedin.__main__:main'

[tool.poetry.dependencies]
python = "^3.7"
linkedin-api = "~=2.0.0a"
mautrix = "^0.9.2"
"ruamel.yaml" = "^0.17.7"
commonmark = "^0.9.1"
SQLAlchemy = "^1.4.17"

[tool.poetry.dev-dependencies]
black = "^21.5b2"
mypy = "^0.812"
flake8 = "^3.9.2"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
