# Tests on Python 3.7+
name: Python

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.2

    - name: Install dependencies
      run: |
        poetry install

    - name: Run lint with black
      run: |
        poetry run black --check .

    - name: Lint with flake8
      if: always()
      run: |
        poetry run flake8 --count --statistics

    - name: Lint with mypy
      if: always()
      run: |
        poetry run mypy linkedin_matrix

    - name: Run custom style checks
      if: always()
      run: |
        poetry run cicd/custom_style_check.py

  build:
    name: Build linkedin_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.2
    - name: Run build
      run: |
        poetry build

  test_deploy:
    name: Test Deploy to PyPi
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.2

    - name: Run build
      run: |
        poetry build

    - name: Dry run publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_DEPLOY_TOKEN }}
        poetry publish --dry-run

  deploy:
    name: Deploy to PyPi
    runs-on: ubuntu-latest
    needs: [test_deploy]
    if: ${{ github.event_name == 'release' && github.event.action == 'created' }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.2

    - name: Run build
      run: |
        poetry build

    - name: Actual publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_DEPLOY_TOKEN }}
        poetry publish
